# SwiftLint Configuration for Fueki Mobile Wallet

# Paths
included:
  - src
excluded:
  - Pods
  - .build
  - .swiftpm
  - Tests/LinuxMain.swift

# Rules
disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces

# Rule Configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

# Custom Rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '(print\(|debugPrint\()'
    match_kinds:
      - identifier
    message: "Use proper logging instead of print()"
    severity: warning

  no_force_cast:
    name: "No Force Casting"
    regex: 'as!'
    message: "Use conditional casting (as?) instead of force casting (as!)"
    severity: error

  crypto_random:
    name: "Secure Random for Crypto"
    regex: 'arc4random|random\(\)'
    message: "Use SecRandomCopyBytes for cryptographic operations"
    severity: warning

  hardcoded_secrets:
    name: "No Hardcoded Secrets"
    regex: '(password|apiKey|privateKey|secret)\s*=\s*"[^"]+"'
    message: "Don't hardcode secrets. Use secure storage."
    severity: error

# Reporter
reporter: "github-actions-logging"
