disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - modifier_order
  - closure_spacing
  - contains_over_first_not_nil

excluded:
  - Pods
  - FuekiWallet/Preview Content
  - Build
  - DerivedData

line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - URL

reporter: "xcode"
