name: Nightly Tests

on:
  schedule:
    - cron: '0 2 * * *' # Run at 2 AM UTC daily
  workflow_dispatch:

env:
  XCODE_VERSION: '15.0'

jobs:
  comprehensive-tests:
    name: Comprehensive Test Suite
    runs-on: macos-13
    timeout-minutes: 90
    strategy:
      matrix:
        device: ['iPhone 15', 'iPhone 15 Pro Max', 'iPad Pro (12.9-inch) (6th generation)']
        ios: ['17.0']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Start Simulator
        run: |
          xcrun simctl boot "${{ matrix.device }}" || true
          xcrun simctl bootstatus "${{ matrix.device }}"

      - name: Run Full Test Suite
        run: |
          set -o pipefail
          xcodebuild test \
            -scheme FuekiWallet \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios }}' \
            -enableCodeCoverage YES \
            -resultBundlePath ./NightlyTests-${{ matrix.device }}.xcresult \
            | xcpretty

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-tests-${{ matrix.device }}
          path: ./NightlyTests-${{ matrix.device }}.xcresult
          retention-days: 30

  performance-tests:
    name: Performance Benchmarks
    runs-on: macos-13
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run Performance Tests
        run: |
          bash scripts/ci/performance-tests.sh

      - name: Upload Performance Report
        uses: actions/upload-artifact@v4
        with:
          name: performance-report
          path: scripts/ci/performance-report.json

  memory-leak-tests:
    name: Memory Leak Detection
    runs-on: macos-13
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Run Memory Leak Tests
        run: |
          bash scripts/ci/memory-leak-tests.sh

      - name: Upload Memory Report
        uses: actions/upload-artifact@v4
        with:
          name: memory-leak-report
          path: scripts/ci/memory-report.json

  notify-results:
    name: Notify Nightly Results
    runs-on: ubuntu-latest
    needs: [comprehensive-tests, performance-tests, memory-leak-tests]
    if: always()

    steps:
      - name: Send Notification
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "Nightly test results for Fueki Wallet",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Nightly Tests Complete*\n\nComprehensive Tests: ${{ needs.comprehensive-tests.result }}\nPerformance Tests: ${{ needs.performance-tests.result }}\nMemory Leak Tests: ${{ needs.memory-leak-tests.result }}"
                  }
                }
              ]
            }
